openapi: 3.0.0
info:
  description: |
    Simple API first driven endpoints
  version: "1.0.0"
  title: "API first"
tags:
  - name: "Get Users"
    description: "Display all users."

servers:
  - url: localhost:8080
paths:
  /users:
    get:
      tags:
        - "Get Users"
      summary: "Display all the users of the Library"
      operationId: "getAllUsers"

      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalError'
components:
  schemas:
    Api-Response:
      type: object
      description: "Response object"
      properties:
        status:
          type: string
          example: 200
        title:
          type: string
          example: "Access granted"

  responses:
    Accepted:
      $ref: '#/components/schemas/Api-Response'

    BadRequest:
      $ref: '#/components/schemas/Api-Response'

    InternalError:
      $ref: '#/components/schemas/Api-Response'
