openapi: 3.0.0
info:
  description: |
    Simple API first driven endpoints
  version: "1.0.0"
  title: "API first"
tags:
  - name: "Get Users"
    description: "Display all users."

servers:
  - url: lslaoang/user/library
paths:
  /users:
    get:
      tags:
        - "Get Users"
      summary: "Display all the users of the Library"
      operationId: "getAllUsers"
      responses:
        200:
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalError'
components:
  schemas:
    responseSchema:
      type: object
      description: "Response object"
      properties:
        status:
          type: string
          example: 200
          default: "200"
        title:
          type: string
          example: "Access granted"
          default: "Access granted"

  responses:
    Accepted:
      description: "Process accepted."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseSchema'

    BadRequest:
      description: "Bad request detected."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseSchema'

    InternalError:
      description: "Server error occurred."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseSchema'
